#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : bats
Version  : 1.11.0
Release  : 30
URL      : https://github.com/bats-core/bats-core/archive/v1.11.0/bats-core-1.11.0.tar.gz
Source0  : https://github.com/bats-core/bats-core/archive/v1.11.0/bats-core-1.11.0.tar.gz
Summary  : Bash Automated Testing System
Group    : Development/Tools
License  : MIT
Requires: bats-bin = %{version}-%{release}
Requires: bats-libexec = %{version}-%{release}
Requires: bats-license = %{version}-%{release}
Requires: bats-man = %{version}-%{release}
Requires: procps-ng
BuildRequires : ncurses-bin
BuildRequires : procps-ng
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: makefile.patch

%description
Bats is a TAP-compliant testing framework for Bash.
It provides a simple way to verify that the UNIX programs you write behave as expected.
Bats is most useful when testing software written in Bash, but you can use it to test any UNIX program.

%package bin
Summary: bin components for the bats package.
Group: Binaries
Requires: bats-libexec = %{version}-%{release}
Requires: bats-license = %{version}-%{release}

%description bin
bin components for the bats package.


%package libexec
Summary: libexec components for the bats package.
Group: Default
Requires: bats-license = %{version}-%{release}

%description libexec
libexec components for the bats package.


%package license
Summary: license components for the bats package.
Group: Default

%description license
license components for the bats package.


%package man
Summary: man components for the bats package.
Group: Default

%description man
man components for the bats package.


%prep
%setup -q -n bats-core-1.11.0
cd %{_builddir}/bats-core-1.11.0
%patch -P 1 -p1
pushd ..
cp -a bats-core-1.11.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719952695
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}

pushd ../buildavx2
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
# From Arch Linux PKGBUILD...
TERM=linux bin/bats --print-output-on-failure --tap test

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719952695
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bats
cp %{_builddir}/bats-core-%{version}/LICENSE.md %{buildroot}/usr/share/package-licenses/bats/1c44d90b844121642b1219f25b6b8ea3240f8cb9 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib/bats-core/common.bash
/usr/lib/bats-core/formatter.bash
/usr/lib/bats-core/preprocessing.bash
/usr/lib/bats-core/semaphore.bash
/usr/lib/bats-core/test_functions.bash
/usr/lib/bats-core/tracing.bash
/usr/lib/bats-core/validator.bash
/usr/lib/bats-core/warnings.bash

%files bin
%defattr(-,root,root,-)
/usr/bin/bats

%files libexec
%defattr(-,root,root,-)
/usr/libexec/bats-core/bats
/usr/libexec/bats-core/bats-exec-file
/usr/libexec/bats-core/bats-exec-suite
/usr/libexec/bats-core/bats-exec-test
/usr/libexec/bats-core/bats-format-cat
/usr/libexec/bats-core/bats-format-junit
/usr/libexec/bats-core/bats-format-pretty
/usr/libexec/bats-core/bats-format-tap
/usr/libexec/bats-core/bats-format-tap13
/usr/libexec/bats-core/bats-gather-tests
/usr/libexec/bats-core/bats-preprocess

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bats/1c44d90b844121642b1219f25b6b8ea3240f8cb9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bats.1
/usr/share/man/man7/bats.7
